services:
  server:
    image: song-lib
    container_name: song-lib
    build:
      context: ..
    restart: always
    env_file:
      - .env
    ports:
      - '${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}'
    depends_on:
      - db
    environment:
      DB_HOST: db

  db:
    container_name: 'song-lib-postgres'
    image: 'postgres:16'
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'